// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxifxtgxO9l1r71HLITla7u_WkatSG90',
    appId: '1:53491370059:web:a474bd92e4ee744f85a5ce',
    messagingSenderId: '53491370059',
    projectId: 'project-7580266658278193147',
    authDomain: 'project-7580266658278193147.firebaseapp.com',
    storageBucket: 'project-7580266658278193147.firebasestorage.app',
    measurementId: 'G-2EDBF7Y003',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKQFleJ69BHkhmf6uYOcuEMPe0LxVv3Lw',
    appId: '1:53491370059:android:21fdd4ca92cd08c185a5ce',
    messagingSenderId: '53491370059',
    projectId: 'project-7580266658278193147',
    storageBucket: 'project-7580266658278193147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcHfsnYhL4vrM_wPoYKPJC5lQL3uCN688',
    appId: '1:53491370059:ios:96745051ddfa1db885a5ce',
    messagingSenderId: '53491370059',
    projectId: 'project-7580266658278193147',
    storageBucket: 'project-7580266658278193147.firebasestorage.app',
    iosBundleId: 'com.example.flutter2048',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcHfsnYhL4vrM_wPoYKPJC5lQL3uCN688',
    appId: '1:53491370059:ios:96745051ddfa1db885a5ce',
    messagingSenderId: '53491370059',
    projectId: 'project-7580266658278193147',
    storageBucket: 'project-7580266658278193147.firebasestorage.app',
    iosBundleId: 'com.example.flutter2048',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfxifxtgxO9l1r71HLITla7u_WkatSG90',
    appId: '1:53491370059:web:3c554787130f128e85a5ce',
    messagingSenderId: '53491370059',
    projectId: 'project-7580266658278193147',
    authDomain: 'project-7580266658278193147.firebaseapp.com',
    storageBucket: 'project-7580266658278193147.firebasestorage.app',
    measurementId: 'G-Z7P90TJW4Z',
  );
}
