name: flutter_2048
description: A 2048 game built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  firebase_core: ^2.17.0
  firebase_database: ^10.0.6
  cloud_firestore: ^4.17.5
  provider: ^6.1.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

